-- AlterTable
ALTER TABLE "invoices" ALTER COLUMN "amount_electricity" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "amount_sceee" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "amount_compensated" SET DATA TYPE DOUBLE PRECISION;
